# Generated by Django 4.0.3 on 2022-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_sold_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.CharField(blank=True, choices=[('Unique', 'Unique'), ('Multiple', 'Multiple'), ('Sold', 'Sold')], default='Unique', max_length=8, null=True),
        ),
    ]
