# Generated by Django 4.0.3 on 2022-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_quantity_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.CharField(choices=[('Unique', 'Unique'), ('Multiple', 'Multiple'), ('Sold', 'Sold')], default='Unique', max_length=8),
        ),
    ]
