# Generated by Django 4.0.3 on 2022-03-24 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_customer_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='exit', max_length=22, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^[0-9+]+$')]),
            preserve_default=False,
        ),
    ]
