# Generated by Django 4.0.3 on 2022-03-24 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^[0-9+\\s]+$')]),
        ),
    ]
