# Generated by Django 4.0.3 on 2022-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decoration',
            field=models.CharField(default='Handmade', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='100% cotton', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='36 / 40 cm', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='straps',
            field=models.TextField(default='Long straps suitable for carrying by hand or over the shoulder', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='washable',
            field=models.CharField(default='30 °C', max_length=32),
        ),
    ]
