# Generated by Django 4.0.3 on 2022-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_decoration_product_material_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
